[package]
name = "menur"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
description = "a dmenu-like launcher written in rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.4.13"
